adminUser:
  password: vault:tekton-squirrel/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  token: vault:tekton-squirrel/pipelineUser:token
  username: jenkins-x-bot
prow:
  hmacToken: vault:tekton-squirrel/prow:hmacToken
